class CapitalCity {
  final String city;
  final String country;
  final String countryCode;
  final double latitude;
  final double longitude;

  const CapitalCity({
    required this.city,
    required this.country,
    required this.countryCode,
    required this.latitude,
    required this.longitude,
  });

  String get displayName => '$city, $country';

  Map<String, dynamic> toJson() {
    return {
      'city': city,
      'country': country,
      'countryCode': countryCode,
      'latitude': latitude,
      'longitude': longitude,
      'searchText': displayName.toLowerCase(),
    };
  }

  factory CapitalCity.fromJson(Map<String, dynamic> json) {
    return CapitalCity(
      city: json['city'] as String? ?? '',
      country: json['country'] as String? ?? '',
      countryCode: json['countryCode'] as String? ?? '',
      latitude: (json['latitude'] as num?)?.toDouble() ?? 0,
      longitude: (json['longitude'] as num?)?.toDouble() ?? 0,
    );
  }
}

const fallbackCapitalCities = <CapitalCity>[
  CapitalCity(
    city: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 30.0444,
    longitude: 31.2357,
  ),
  CapitalCity(
    city: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 24.7136,
    longitude: 46.6753,
  ),
  CapitalCity(
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 24.4539,
    longitude: 54.3773,
  ),
  CapitalCity(
    city: 'Doha',
    country: 'Qatar',
    countryCode: 'QA',
    latitude: 25.2854,
    longitude: 51.531,
  ),
  CapitalCity(
    city: 'Kuwait City',
    country: 'Kuwait',
    countryCode: 'KW',
    latitude: 29.3759,
    longitude: 47.9774,
  ),
  CapitalCity(
    city: 'Manama',
    country: 'Bahrain',
    countryCode: 'BH',
    latitude: 26.2235,
    longitude: 50.5876,
  ),
  CapitalCity(
    city: 'Muscat',
    country: 'Oman',
    countryCode: 'OM',
    latitude: 23.588,
    longitude: 58.3829,
  ),
  CapitalCity(
    city: 'Amman',
    country: 'Jordan',
    countryCode: 'JO',
    latitude: 31.9539,
    longitude: 35.9106,
  ),
  CapitalCity(
    city: 'Beirut',
    country: 'Lebanon',
    countryCode: 'LB',
    latitude: 33.8938,
    longitude: 35.5018,
  ),
  CapitalCity(
    city: 'Damascus',
    country: 'Syria',
    countryCode: 'SY',
    latitude: 33.5138,
    longitude: 36.2765,
  ),
  CapitalCity(
    city: 'Baghdad',
    country: 'Iraq',
    countryCode: 'IQ',
    latitude: 33.3152,
    longitude: 44.3661,
  ),
  CapitalCity(
    city: 'Sanaa',
    country: 'Yemen',
    countryCode: 'YE',
    latitude: 15.3694,
    longitude: 44.191,
  ),
  CapitalCity(
    city: 'Khartoum',
    country: 'Sudan',
    countryCode: 'SD',
    latitude: 15.5007,
    longitude: 32.5599,
  ),
  CapitalCity(
    city: 'Tripoli',
    country: 'Libya',
    countryCode: 'LY',
    latitude: 32.8872,
    longitude: 13.1913,
  ),
  CapitalCity(
    city: 'Tunis',
    country: 'Tunisia',
    countryCode: 'TN',
    latitude: 36.8065,
    longitude: 10.1815,
  ),
  CapitalCity(
    city: 'Algiers',
    country: 'Algeria',
    countryCode: 'DZ',
    latitude: 36.7538,
    longitude: 3.0588,
  ),
  CapitalCity(
    city: 'Rabat',
    country: 'Morocco',
    countryCode: 'MA',
    latitude: 34.0209,
    longitude: -6.8416,
  ),
  CapitalCity(
    city: 'Nouakchott',
    country: 'Mauritania',
    countryCode: 'MR',
    latitude: 18.0735,
    longitude: -15.9582,
  ),
  CapitalCity(
    city: 'Mogadishu',
    country: 'Somalia',
    countryCode: 'SO',
    latitude: 2.0469,
    longitude: 45.3182,
  ),
  CapitalCity(
    city: 'Djibouti',
    country: 'Djibouti',
    countryCode: 'DJ',
    latitude: 11.5721,
    longitude: 43.1456,
  ),
  CapitalCity(
    city: 'Ankara',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 39.9334,
    longitude: 32.8597,
  ),
  CapitalCity(
    city: 'Tehran',
    country: 'Iran',
    countryCode: 'IR',
    latitude: 35.6892,
    longitude: 51.389,
  ),
  CapitalCity(
    city: 'Islamabad',
    country: 'Pakistan',
    countryCode: 'PK',
    latitude: 33.6844,
    longitude: 73.0479,
  ),
  CapitalCity(
    city: 'Kabul',
    country: 'Afghanistan',
    countryCode: 'AF',
    latitude: 34.5553,
    longitude: 69.2075,
  ),
  CapitalCity(
    city: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    latitude: -6.2088,
    longitude: 106.8456,
  ),
  CapitalCity(
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    latitude: 3.139,
    longitude: 101.6869,
  ),
  CapitalCity(
    city: 'Bandar Seri Begawan',
    country: 'Brunei',
    countryCode: 'BN',
    latitude: 4.9031,
    longitude: 114.9398,
  ),
  CapitalCity(
    city: 'Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    latitude: 23.8103,
    longitude: 90.4125,
  ),
  CapitalCity(
    city: 'Male',
    country: 'Maldives',
    countryCode: 'MV',
    latitude: 4.1755,
    longitude: 73.5093,
  ),
  CapitalCity(
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.5072,
    longitude: -0.1276,
  ),
  CapitalCity(
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 48.8566,
    longitude: 2.3522,
  ),
  CapitalCity(
    city: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    latitude: 52.52,
    longitude: 13.405,
  ),
  CapitalCity(
    city: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    latitude: 41.9028,
    longitude: 12.4964,
  ),
  CapitalCity(
    city: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    latitude: 40.4168,
    longitude: -3.7038,
  ),
  CapitalCity(
    city: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    latitude: 38.7223,
    longitude: -9.1393,
  ),
  CapitalCity(
    city: 'Brussels',
    country: 'Belgium',
    countryCode: 'BE',
    latitude: 50.8503,
    longitude: 4.3517,
  ),
  CapitalCity(
    city: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    latitude: 52.3676,
    longitude: 4.9041,
  ),
  CapitalCity(
    city: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    latitude: 48.2082,
    longitude: 16.3738,
  ),
  CapitalCity(
    city: 'Bern',
    country: 'Switzerland',
    countryCode: 'CH',
    latitude: 46.948,
    longitude: 7.4474,
  ),
  CapitalCity(
    city: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    latitude: 59.3293,
    longitude: 18.0686,
  ),
  CapitalCity(
    city: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    latitude: 59.9139,
    longitude: 10.7522,
  ),
  CapitalCity(
    city: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    latitude: 55.6761,
    longitude: 12.5683,
  ),
  CapitalCity(
    city: 'Helsinki',
    country: 'Finland',
    countryCode: 'FI',
    latitude: 60.1699,
    longitude: 24.9384,
  ),
  CapitalCity(
    city: 'Dublin',
    country: 'Ireland',
    countryCode: 'IE',
    latitude: 53.3498,
    longitude: -6.2603,
  ),
  CapitalCity(
    city: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    latitude: 37.9838,
    longitude: 23.7275,
  ),
  CapitalCity(
    city: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    latitude: 52.2297,
    longitude: 21.0122,
  ),
  CapitalCity(
    city: 'Prague',
    country: 'Czechia',
    countryCode: 'CZ',
    latitude: 50.0755,
    longitude: 14.4378,
  ),
  CapitalCity(
    city: 'Budapest',
    country: 'Hungary',
    countryCode: 'HU',
    latitude: 47.4979,
    longitude: 19.0402,
  ),
  CapitalCity(
    city: 'Bucharest',
    country: 'Romania',
    countryCode: 'RO',
    latitude: 44.4268,
    longitude: 26.1025,
  ),
  CapitalCity(
    city: 'Sofia',
    country: 'Bulgaria',
    countryCode: 'BG',
    latitude: 42.6977,
    longitude: 23.3219,
  ),
  CapitalCity(
    city: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 55.7558,
    longitude: 37.6173,
  ),
  CapitalCity(
    city: 'Kyiv',
    country: 'Ukraine',
    countryCode: 'UA',
    latitude: 50.4501,
    longitude: 30.5234,
  ),
  CapitalCity(
    city: 'Washington, D.C.',
    country: 'United States',
    countryCode: 'US',
    latitude: 38.9072,
    longitude: -77.0369,
  ),
  CapitalCity(
    city: 'Ottawa',
    country: 'Canada',
    countryCode: 'CA',
    latitude: 45.4215,
    longitude: -75.6972,
  ),
  CapitalCity(
    city: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    latitude: 19.4326,
    longitude: -99.1332,
  ),
  CapitalCity(
    city: 'Brasilia',
    country: 'Brazil',
    countryCode: 'BR',
    latitude: -15.7939,
    longitude: -47.8828,
  ),
  CapitalCity(
    city: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    latitude: -34.6037,
    longitude: -58.3816,
  ),
  CapitalCity(
    city: 'Santiago',
    country: 'Chile',
    countryCode: 'CL',
    latitude: -33.4489,
    longitude: -70.6693,
  ),
  CapitalCity(
    city: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    latitude: -12.0464,
    longitude: -77.0428,
  ),
  CapitalCity(
    city: 'Bogota',
    country: 'Colombia',
    countryCode: 'CO',
    latitude: 4.711,
    longitude: -74.0721,
  ),
  CapitalCity(
    city: 'Caracas',
    country: 'Venezuela',
    countryCode: 'VE',
    latitude: 10.4806,
    longitude: -66.9036,
  ),
  CapitalCity(
    city: 'Quito',
    country: 'Ecuador',
    countryCode: 'EC',
    latitude: -0.1807,
    longitude: -78.4678,
  ),
  CapitalCity(
    city: 'La Paz',
    country: 'Bolivia',
    countryCode: 'BO',
    latitude: -16.4897,
    longitude: -68.1193,
  ),
  CapitalCity(
    city: 'Montevideo',
    country: 'Uruguay',
    countryCode: 'UY',
    latitude: -34.9011,
    longitude: -56.1645,
  ),
  CapitalCity(
    city: 'Asuncion',
    country: 'Paraguay',
    countryCode: 'PY',
    latitude: -25.2637,
    longitude: -57.5759,
  ),
  CapitalCity(
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    latitude: 35.6762,
    longitude: 139.6503,
  ),
  CapitalCity(
    city: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    latitude: 37.5665,
    longitude: 126.978,
  ),
  CapitalCity(
    city: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    latitude: 39.9042,
    longitude: 116.4074,
  ),
  CapitalCity(
    city: 'New Delhi',
    country: 'India',
    countryCode: 'IN',
    latitude: 28.6139,
    longitude: 77.209,
  ),
  CapitalCity(
    city: 'Kathmandu',
    country: 'Nepal',
    countryCode: 'NP',
    latitude: 27.7172,
    longitude: 85.324,
  ),
  CapitalCity(
    city: 'Colombo',
    country: 'Sri Lanka',
    countryCode: 'LK',
    latitude: 6.9271,
    longitude: 79.8612,
  ),
  CapitalCity(
    city: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    latitude: 13.7563,
    longitude: 100.5018,
  ),
  CapitalCity(
    city: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    latitude: 21.0278,
    longitude: 105.8342,
  ),
  CapitalCity(
    city: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    latitude: 14.5995,
    longitude: 120.9842,
  ),
  CapitalCity(
    city: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    latitude: 1.3521,
    longitude: 103.8198,
  ),
  CapitalCity(
    city: 'Canberra',
    country: 'Australia',
    countryCode: 'AU',
    latitude: -35.2809,
    longitude: 149.13,
  ),
  CapitalCity(
    city: 'Wellington',
    country: 'New Zealand',
    countryCode: 'NZ',
    latitude: -41.2865,
    longitude: 174.7762,
  ),
  CapitalCity(
    city: 'Pretoria',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -25.7479,
    longitude: 28.2293,
  ),
  CapitalCity(
    city: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    latitude: -1.2921,
    longitude: 36.8219,
  ),
  CapitalCity(
    city: 'Addis Ababa',
    country: 'Ethiopia',
    countryCode: 'ET',
    latitude: 8.9806,
    longitude: 38.7578,
  ),
  CapitalCity(
    city: 'Kampala',
    country: 'Uganda',
    countryCode: 'UG',
    latitude: 0.3476,
    longitude: 32.5825,
  ),
  CapitalCity(
    city: 'Dodoma',
    country: 'Tanzania',
    countryCode: 'TZ',
    latitude: -6.163,
    longitude: 35.7516,
  ),
  CapitalCity(
    city: 'Kigali',
    country: 'Rwanda',
    countryCode: 'RW',
    latitude: -1.9441,
    longitude: 30.0619,
  ),
  CapitalCity(
    city: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.5244,
    longitude: 3.3792,
  ),
  CapitalCity(
    city: 'Accra',
    country: 'Ghana',
    countryCode: 'GH',
    latitude: 5.6037,
    longitude: -0.187,
  ),
  CapitalCity(
    city: 'Dakar',
    country: 'Senegal',
    countryCode: 'SN',
    latitude: 14.7167,
    longitude: -17.4677,
  ),



    CapitalCity(
    city: 'Alexandria',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 31.2001,
    longitude: 29.9187,
  ),
  CapitalCity(
    city: 'Giza',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 30.0131,
    longitude: 31.2089,
  ),
  CapitalCity(
    city: 'Luxor',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 25.6872,
    longitude: 32.6396,
  ),
  CapitalCity(
    city: 'Aswan',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 24.0889,
    longitude: 32.8998,
  ),
    CapitalCity(
    city: 'Jeddah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 21.4858,
    longitude: 39.1925,
  ),
  CapitalCity(
    city: 'Mecca',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 21.3891,
    longitude: 39.8579,
  ),
  CapitalCity(
    city: 'Medina',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    latitude: 24.5247,
    longitude: 39.5692,
  ),
];
