// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdwEKCqKvVS3mIKVrHvW6uGjF2ZksNXxA',
    appId: '1:52234340227:web:7a32b60521de553dead8b6',
    messagingSenderId: '52234340227',
    projectId: 'final-project-84d31',
    authDomain: 'final-project-84d31.firebaseapp.com',
    storageBucket: 'final-project-84d31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSgHg3O5H5STG0IOghyTpkpGzcwrOKvU',
    appId: '1:52234340227:android:9e826513d6838806ead8b6',
    messagingSenderId: '52234340227',
    projectId: 'final-project-84d31',
    storageBucket: 'final-project-84d31.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwJ4s902QDG9gaDjdz6tik5hyxmll9aM',
    appId: '1:52234340227:ios:4ec37c831ca0cb99ead8b6',
    messagingSenderId: '52234340227',
    projectId: 'final-project-84d31',
    storageBucket: 'final-project-84d31.firebasestorage.app',
    iosBundleId: 'com.example.noorah',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALwJ4s902QDG9gaDjdz6tik5hyxmll9aM',
    appId: '1:52234340227:ios:4ec37c831ca0cb99ead8b6',
    messagingSenderId: '52234340227',
    projectId: 'final-project-84d31',
    storageBucket: 'final-project-84d31.firebasestorage.app',
    iosBundleId: 'com.example.noorah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdwEKCqKvVS3mIKVrHvW6uGjF2ZksNXxA',
    appId: '1:52234340227:web:5549c8f2caeb1aafead8b6',
    messagingSenderId: '52234340227',
    projectId: 'final-project-84d31',
    authDomain: 'final-project-84d31.firebaseapp.com',
    storageBucket: 'final-project-84d31.firebasestorage.app',
  );
}
